package com.attendance.manage.service;

import com.attendance.manage.model.LeaveType;
import java.util.List;

public interface LeaveTypeService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table leave_type
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table leave_type
	 * @mbggenerated
	 */
	int insert(LeaveType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table leave_type
	 * @mbggenerated
	 */
	LeaveType selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table leave_type
	 * @mbggenerated
	 */
	List<LeaveType> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table leave_type
	 * @mbggenerated
	 */
	int updateByPrimaryKey(LeaveType record);
}