package com.attendance.manage.service;
import com.attendance.manage.model.OutRequest;

import java.util.HashMap;
import java.util.List;

public interface OutRequestService {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_request
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_request
     *
     * @mbggenerated
     */
    int insert(OutRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_request
     *
     * @mbggenerated
     */
    OutRequest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_request
     *
     * @mbggenerated
     */
    List<OutRequest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_request
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OutRequest record);
    
    List<OutRequest> selectApproveByID(HashMap<String,Object> paraMap);
    /**
     * 申请
     */
    void newApply(OutRequest outRequest);
    
    List<OutRequest> findMyApplyByStuffId(HashMap<String,Object> paraMap);
    
    //查询我的申请各种状态数量
    HashMap<String,Integer> findMyApplyAllConut(Long id);
    //查询我的审批各种状态的数量
    HashMap<String,Integer> findMyApproveAllConut(Long id);
    
    HashMap<String,Object> findApplyDetailByID(Long id);
}