package com.attendance.manage.service;

import com.attendance.manage.model.OutRequest;
import java.util.List;

public interface OutRequestService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table out_request
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table out_request
	 * @mbggenerated
	 */
	int insert(OutRequest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table out_request
	 * @mbggenerated
	 */
	OutRequest selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table out_request
	 * @mbggenerated
	 */
	List<OutRequest> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table out_request
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OutRequest record);
}