package com.attendance.manage.service;

import java.util.List;

import com.attendance.manage.model.RoleAuthority;

public interface RoleAuthorityService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_authority
	 * 
	 * @mbggenerated
	 */
	int insert(RoleAuthority record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_authority
	 * 
	 * @mbggenerated
	 */
	List<RoleAuthority> selectAll();

	int updateByPrimaryKey(RoleAuthority roleAuthority);

	RoleAuthority selectByPrimaryKey(Long id);

	int deleteByPrimaryKey(Long id);
}