package com.attendance.manage.service;

import java.util.List;

import com.attendance.manage.model.Stuff;

public interface StuffService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stuff
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stuff
	 * 
	 * @mbggenerated
	 */
	int insert(Stuff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stuff
	 * 
	 * @mbggenerated
	 */
	Stuff selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stuff
	 * 
	 * @mbggenerated
	 */
	List<Stuff> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stuff
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Stuff record);

	boolean usernameExists(String username);

	public Stuff findByUsername(String username);
	public Stuff findUserInfo(String username);

	public List<String> findAuthorities(Long id);
	
	

}