package com.attendance.manage.service;

import com.attendance.manage.model.SystemConfig;
import java.util.List;

public interface SystemConfigService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_config
	 * @mbggenerated
	 */
	int insert(SystemConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_config
	 * @mbggenerated
	 */
	List<SystemConfig> selectAll();
}