package com.attendance.manage.service;

import java.util.List;

import com.attendance.manage.model.SystemConfig;

public interface SystemConfigService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table system_config
	 * 
	 * @mbggenerated
	 */
	int insert(SystemConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table system_config
	 * 
	 * @mbggenerated
	 */
	List<SystemConfig> selectAll();

	SystemConfig selectByKey(String key);

	int updateByKey(SystemConfig systemConfig);

	int deleteByKey(String key);
}