package com.attendance.manage.service.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.attendance.manage.dao.CheckInfoMapper;
import com.attendance.manage.model.CheckInfo;
import com.attendance.manage.service.CheckInfoService;

@Service
public class CheckInfoServiceImpl implements CheckInfoService {
	@Autowired
	private CheckInfoMapper checkInfoDao;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table check_info
	 * 
	 * @mbggenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		return checkInfoDao.deleteByPrimaryKey(id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table check_info
	 * 
	 * @mbggenerated
	 */
	public int insert(CheckInfo record) {
		return checkInfoDao.insert(record);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table check_info
	 * 
	 * @mbggenerated
	 */
	public CheckInfo selectByPrimaryKey(Long id) {
		return checkInfoDao.selectByPrimaryKey(id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table check_info
	 * 
	 * @mbggenerated
	 */
	public List<CheckInfo> selectAll() {
		return checkInfoDao.selectAll();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table check_info
	 * 
	 * @mbggenerated
	 */
	public int updateByPrimaryKey(CheckInfo record) {
		return checkInfoDao.updateByPrimaryKey(record);
	}
}