package com.attendance.manage.service.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.attendance.manage.dao.LeaveTypeMapper;
import com.attendance.manage.model.LeaveType;
import com.attendance.manage.service.LeaveTypeService;

@Service
public class LeaveTypeServiceImpl implements LeaveTypeService {
	@Autowired
	private LeaveTypeMapper leaveTypeDao;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table leave_type
	 * 
	 * @mbggenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		return leaveTypeDao.deleteByPrimaryKey(id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table leave_type
	 * 
	 * @mbggenerated
	 */
	public int insert(LeaveType record) {
		return leaveTypeDao.insert(record);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table leave_type
	 * 
	 * @mbggenerated
	 */
	public LeaveType selectByPrimaryKey(Long id) {
		return leaveTypeDao.selectByPrimaryKey(id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table leave_type
	 * 
	 * @mbggenerated
	 */
	public List<LeaveType> selectAll() {
		return leaveTypeDao.selectAll();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table leave_type
	 * 
	 * @mbggenerated
	 */
	public int updateByPrimaryKey(LeaveType record) {
		return leaveTypeDao.updateByPrimaryKey(record);
	}
}