package com.attendance.manage.service.impl;

import java.util.HashMap;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.attendance.manage.dao.LeaveRequestMapper;
import com.attendance.manage.model.LeaveRequest;
import com.attendance.manage.service.LeaveRequestService;

@Service
public class LeaveRequestServiceImpl implements LeaveRequestService {
	@Autowired
	private LeaveRequestMapper leaveRequestDao;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table leave_request
	 * 
	 * @mbggenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		return leaveRequestDao.deleteByPrimaryKey(id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table leave_request
	 * 
	 * @mbggenerated
	 */
	public int insert(LeaveRequest record) {
		return leaveRequestDao.insert(record);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table leave_request
	 * 
	 * @mbggenerated
	 */
	public LeaveRequest selectByPrimaryKey(Long id) {
		return leaveRequestDao.selectByPrimaryKey(id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table leave_request
	 * 
	 * @mbggenerated
	 */
	public List<LeaveRequest> selectAll() {
		return leaveRequestDao.selectAll();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table leave_request
	 * 
	 * @mbggenerated
	 */
	public int updateByPrimaryKey(LeaveRequest record) {
		return leaveRequestDao.updateByPrimaryKey(record);
	}
	
	public List<LeaveRequest> selectApproveByID(HashMap<String,Object> paraMap){
		List<LeaveRequest> approveList=leaveRequestDao.selectApproveByID(paraMap);
		return approveList;
	}
	/**
     * 申请
     */
    public void newApply(LeaveRequest leaveRequest){
    	leaveRequestDao.insert(leaveRequest);
    }
    public List<LeaveRequest> findMyApplyByStuffId(HashMap<String,Object> paraMap){
    	
    	return leaveRequestDao.findMyApplyByStuffId(paraMap);
    }
    //查询我的申请各种状态数量
   public HashMap<String,Integer> findMyApplyAllConut(Long id){
	   return leaveRequestDao.findMyApplyAllConut(id);
    }
    //查询我的审批各种状态的数量
   public HashMap<String,Integer> findMyApproveAllConut(Long id){
	   return leaveRequestDao.findMyApproveAllConut(id);
   }
   
   public HashMap<String,Object> findApplyDetailByID(Long id){
	   return leaveRequestDao.findApplyDetailByID(id);
   }
}