package com.attendance.manage.service.impl;

import java.util.HashMap;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.attendance.manage.dao.OutRequestMapper;
import com.attendance.manage.model.OutRequest;
import com.attendance.manage.service.OutRequestService;

@Service
public class OutRequestServiceImpl implements OutRequestService {
	@Autowired
	private OutRequestMapper outRequestDao;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table leave_request
	 * 
	 * @mbggenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		return outRequestDao.deleteByPrimaryKey(id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table leave_request
	 * 
	 * @mbggenerated
	 */
	public int insert(OutRequest record) {
		return outRequestDao.insert(record);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table leave_request
	 * 
	 * @mbggenerated
	 */
	public OutRequest selectByPrimaryKey(Long id) {
		return outRequestDao.selectByPrimaryKey(id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table leave_request
	 * 
	 * @mbggenerated
	 */
	public List<OutRequest> selectAll() {
		return outRequestDao.selectAll();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table leave_request
	 * 
	 * @mbggenerated
	 */
	public int updateByPrimaryKey(OutRequest record) {
		return outRequestDao.updateByPrimaryKey(record);
	}
	
	public List<OutRequest> selectApproveByID(HashMap<String,Object> paraMap){
		List<OutRequest> approveList=outRequestDao.selectApproveByID(paraMap);
		return approveList;
	}
	/**
     * 申请
     */
    public void newApply(OutRequest outRequest){
    	outRequestDao.insert(outRequest);
    }
    public List<OutRequest> findMyApplyByStuffId(HashMap<String,Object> paraMap){
    	
    	return outRequestDao.findMyApplyByStuffId(paraMap);
    }
    //查询我的申请各种状态数量
   public HashMap<String,Integer> findMyApplyAllConut(Long id){
	   return outRequestDao.findMyApplyAllConut(id);
    }
    //查询我的审批各种状态的数量
   public HashMap<String,Integer> findMyApproveAllConut(Long id){
	   return outRequestDao.findMyApproveAllConut(id);
   }
   
   public HashMap<String,Object> findApplyDetailByID(Long id){
	   return outRequestDao.findApplyDetailByID(id);
   }
}