package com.attendance.manage.service.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.attendance.manage.dao.OutRequestMapper;
import com.attendance.manage.model.OutRequest;
import com.attendance.manage.service.OutRequestService;

@Service
public class OutRequestServiceImpl implements OutRequestService {
	@Autowired
	private OutRequestMapper outRequestDao;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table out_request
	 * 
	 * @mbggenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		return outRequestDao.deleteByPrimaryKey(id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table out_request
	 * 
	 * @mbggenerated
	 */
	public int insert(OutRequest record) {
		return outRequestDao.insert(record);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table out_request
	 * 
	 * @mbggenerated
	 */
	public OutRequest selectByPrimaryKey(Long id) {
		return outRequestDao.selectByPrimaryKey(id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table out_request
	 * 
	 * @mbggenerated
	 */
	public List<OutRequest> selectAll() {
		return outRequestDao.selectAll();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table out_request
	 * 
	 * @mbggenerated
	 */
	public int updateByPrimaryKey(OutRequest record) {
		return outRequestDao.updateByPrimaryKey(record);
	}
}