package com.attendance.manage.service.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.attendance.manage.dao.RoleAuthorityMapper;
import com.attendance.manage.model.RoleAuthority;
import com.attendance.manage.service.RoleAuthorityService;

@Service
public class RoleAuthorityServiceImpl implements RoleAuthorityService {
	@Autowired
	private RoleAuthorityMapper roleAuthorityDao;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_authority
	 * 
	 * @mbggenerated
	 */
	public int insert(RoleAuthority record) {
		return roleAuthorityDao.insert(record);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_authority
	 * 
	 * @mbggenerated
	 */
	public List<RoleAuthority> selectAll() {
		return roleAuthorityDao.selectAll();
	}

	public int updateByPrimaryKey(RoleAuthority roleAuthority) {

		return roleAuthorityDao.updateByPrimaryKey(roleAuthority);
	}

	public RoleAuthority selectByPrimaryKey(Long id) {

		return roleAuthorityDao.selectByPrimaryKey(id);
	}

	public int deleteByPrimaryKey(Long id) {

		return roleAuthorityDao.deleteByPrimaryKey(id);
	}
}