package com.attendance.manage.service.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.attendance.manage.dao.RoleMapper;
import com.attendance.manage.model.Role;
import com.attendance.manage.service.RoleService;

@Service
public class RoleServiceImpl implements RoleService {
	@Autowired
	private RoleMapper roleDao;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 * 
	 * @mbggenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		return roleDao.deleteByPrimaryKey(id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 * 
	 * @mbggenerated
	 */
	public int insert(Role record) {
		return roleDao.insert(record);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 * 
	 * @mbggenerated
	 */
	public Role selectByPrimaryKey(Long id) {
		return roleDao.selectByPrimaryKey(id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 * 
	 * @mbggenerated
	 */
	public List<Role> selectAll() {
		return roleDao.selectAll();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 * 
	 * @mbggenerated
	 */
	public int updateByPrimaryKey(Role record) {
		return roleDao.updateByPrimaryKey(record);
	}
}