package com.attendance.manage.service.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.attendance.manage.dao.StuffRoleMapper;
import com.attendance.manage.model.StuffRole;
import com.attendance.manage.service.StuffRoleService;

@Service
public class StuffRoleServiceImpl implements StuffRoleService {
	@Autowired
	private StuffRoleMapper stuffRoleDao;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stuff_role
	 * 
	 * @mbggenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		return stuffRoleDao.deleteByPrimaryKey(id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stuff_role
	 * 
	 * @mbggenerated
	 */
	public int insert(StuffRole record) {
		return stuffRoleDao.insert(record);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stuff_role
	 * 
	 * @mbggenerated
	 */
	public StuffRole selectByPrimaryKey(Long id) {
		return stuffRoleDao.selectByPrimaryKey(id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stuff_role
	 * 
	 * @mbggenerated
	 */
	public List<StuffRole> selectAll() {
		return stuffRoleDao.selectAll();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stuff_role
	 * 
	 * @mbggenerated
	 */
	public int updateByPrimaryKey(StuffRole record) {
		return stuffRoleDao.updateByPrimaryKey(record);
	}
}