package com.attendance.manage.service.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.attendance.manage.dao.SystemConfigMapper;
import com.attendance.manage.model.SystemConfig;
import com.attendance.manage.service.SystemConfigService;

@Service
public class SystemConfigServiceImpl implements SystemConfigService {
	@Autowired
	private SystemConfigMapper systemConfigDao;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table system_config
	 * 
	 * @mbggenerated
	 */
	public int insert(SystemConfig record) {
		return systemConfigDao.insert(record);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table system_config
	 * 
	 * @mbggenerated
	 */
	public List<SystemConfig> selectAll() {
		return systemConfigDao.selectAll();
	}
}