package com.attendance.manage.dao;

import com.attendance.manage.model.CheckInfo;
import java.util.List;

public interface CheckInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_info
     *
     * @mbggenerated
     */
    int insert(CheckInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_info
     *
     * @mbggenerated
     */
    CheckInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_info
     *
     * @mbggenerated
     */
    List<CheckInfo> selectAll();
    
    List<CheckInfo> selectAllAndSort();
    
    List<CheckInfo> selectAllStartAndEndTimes();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CheckInfo record);
    
}