package com.attendance.manage.dao;

import com.attendance.manage.model.Department;
import java.util.List;

public interface DepartmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbggenerated
	 */
	int insert(Department record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbggenerated
	 */
	Department selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbggenerated
	 */
	List<Department> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Department record);
}