package com.attendance.manage.dao;

import com.attendance.manage.model.OutType;
import java.util.List;

public interface OutTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table out_type
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table out_type
	 * @mbggenerated
	 */
	int insert(OutType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table out_type
	 * @mbggenerated
	 */
	OutType selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table out_type
	 * @mbggenerated
	 */
	List<OutType> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table out_type
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OutType record);
}