package com.attendance.manage.dao;

import com.attendance.manage.model.StuffRole;
import java.util.List;

public interface StuffRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stuff_role
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stuff_role
	 * @mbggenerated
	 */
	int insert(StuffRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stuff_role
	 * @mbggenerated
	 */
	StuffRole selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stuff_role
	 * @mbggenerated
	 */
	List<StuffRole> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stuff_role
	 * @mbggenerated
	 */
	int updateByPrimaryKey(StuffRole record);
}