package com.attendance.manage.dao;

import java.util.List;

import com.attendance.manage.model.Stuff;

public interface StuffMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stuff
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stuff
	 * 
	 * @mbggenerated
	 */
	int insert(Stuff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stuff
	 * 
	 * @mbggenerated
	 */
	Stuff selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stuff
	 * 
	 * @mbggenerated
	 */
	List<Stuff> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stuff
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Stuff record);

	Stuff findByUsername(String username);

}