package com.attendance.manage.model;

import java.util.Date;

public class LeaveRequest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_request.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_request.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_request.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_request.stuff_id
     *
     * @mbggenerated
     */
    private Long stuffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_request.application_time
     *
     * @mbggenerated
     */
    private Date applicationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_request.begin_time
     *
     * @mbggenerated
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_request.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_request.type_id
     *
     * @mbggenerated
     */
    private Long typeId;
    private String typeName;

    public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_request.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_request.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_request.last_handler
     *
     * @mbggenerated
     */
    private Long lastHandler;
    private String lastHandlerName;
    

    public String getLastHandlerName() {
		return lastHandlerName;
	}

	public void setLastHandlerName(String lastHandlerName) {
		this.lastHandlerName = lastHandlerName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_request.id
     *
     * @return the value of leave_request.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_request.id
     *
     * @param id the value for leave_request.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_request.create_date
     *
     * @return the value of leave_request.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_request.create_date
     *
     * @param createDate the value for leave_request.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_request.modify_date
     *
     * @return the value of leave_request.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_request.modify_date
     *
     * @param modifyDate the value for leave_request.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_request.stuff_id
     *
     * @return the value of leave_request.stuff_id
     *
     * @mbggenerated
     */
    public Long getStuffId() {
        return stuffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_request.stuff_id
     *
     * @param stuffId the value for leave_request.stuff_id
     *
     * @mbggenerated
     */
    public void setStuffId(Long stuffId) {
        this.stuffId = stuffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_request.application_time
     *
     * @return the value of leave_request.application_time
     *
     * @mbggenerated
     */
    public Date getApplicationTime() {
        return applicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_request.application_time
     *
     * @param applicationTime the value for leave_request.application_time
     *
     * @mbggenerated
     */
    public void setApplicationTime(Date applicationTime) {
        this.applicationTime = applicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_request.begin_time
     *
     * @return the value of leave_request.begin_time
     *
     * @mbggenerated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_request.begin_time
     *
     * @param beginTime the value for leave_request.begin_time
     *
     * @mbggenerated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_request.end_time
     *
     * @return the value of leave_request.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_request.end_time
     *
     * @param endTime the value for leave_request.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_request.type_id
     *
     * @return the value of leave_request.type_id
     *
     * @mbggenerated
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_request.type_id
     *
     * @param typeId the value for leave_request.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_request.description
     *
     * @return the value of leave_request.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_request.description
     *
     * @param description the value for leave_request.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_request.status
     *
     * @return the value of leave_request.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_request.status
     *
     * @param status the value for leave_request.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_request.last_handler
     *
     * @return the value of leave_request.last_handler
     *
     * @mbggenerated
     */
    public Long getLastHandler() {
        return lastHandler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_request.last_handler
     *
     * @param lastHandler the value for leave_request.last_handler
     *
     * @mbggenerated
     */
    public void setLastHandler(Long lastHandler) {
        this.lastHandler = lastHandler;
    }
}