package com.attendance.manage.model;

public class RoleAuthority {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_authority.role
	 * @mbggenerated
	 */
	private Long role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_authority.authorities
	 * @mbggenerated
	 */
	private String authorities;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_authority.role
	 * @return  the value of role_authority.role
	 * @mbggenerated
	 */
	public Long getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_authority.role
	 * @param role  the value for role_authority.role
	 * @mbggenerated
	 */
	public void setRole(Long role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_authority.authorities
	 * @return  the value of role_authority.authorities
	 * @mbggenerated
	 */
	public String getAuthorities() {
		return authorities;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_authority.authorities
	 * @param authorities  the value for role_authority.authorities
	 * @mbggenerated
	 */
	public void setAuthorities(String authorities) {
		this.authorities = authorities == null ? null : authorities.trim();
	}
}