package com.attendance.manage.model;

import java.util.Date;

public class Stuff {

	public static final String PRINCIPAL_ATTRIBUTE_NAME = Stuff.class.getName()
			+ ".PRINCIPAL";
	public static final String USERNAME_COOKIE_NAME = Stuff.class.getName()
			+ ".NAME";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.id
	 * 
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.create_date
	 * 
	 * @mbggenerated
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.modify_date
	 * 
	 * @mbggenerated
	 */
	private Date modifyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.email
	 * 
	 * @mbggenerated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.is_enabled
	 * 
	 * @mbggenerated
	 */
	private Boolean isEnabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.is_locked
	 * 
	 * @mbggenerated
	 */
	private Boolean isLocked;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.locked_date
	 * 
	 * @mbggenerated
	 */
	private Date lockedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.login_date
	 * 
	 * @mbggenerated
	 */
	private Date loginDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.login_failure_count
	 * 
	 * @mbggenerated
	 */
	private Integer loginFailureCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.login_ip
	 * 
	 * @mbggenerated
	 */
	private String loginIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.password
	 * 
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.username
	 * 
	 * @mbggenerated
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.name
	 * 
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.gender
	 * 
	 * @mbggenerated
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.seniority
	 * 
	 * @mbggenerated
	 */
	private Integer seniority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.age
	 * 
	 * @mbggenerated
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.depart
	 * 
	 * @mbggenerated
	 */
	private Long depart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.rank
	 * 
	 * @mbggenerated
	 */
	private Integer rank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.birthday
	 * 
	 * @mbggenerated
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column stuff.employment_date
	 * 
	 * @mbggenerated
	 */
	private Date employmentDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.id
	 * 
	 * @return the value of stuff.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.id
	 * 
	 * @param id
	 *            the value for stuff.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.create_date
	 * 
	 * @return the value of stuff.create_date
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.create_date
	 * 
	 * @param createDate
	 *            the value for stuff.create_date
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.modify_date
	 * 
	 * @return the value of stuff.modify_date
	 * @mbggenerated
	 */
	public Date getModifyDate() {
		return modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.modify_date
	 * 
	 * @param modifyDate
	 *            the value for stuff.modify_date
	 * @mbggenerated
	 */
	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.email
	 * 
	 * @return the value of stuff.email
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.email
	 * 
	 * @param email
	 *            the value for stuff.email
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.is_enabled
	 * 
	 * @return the value of stuff.is_enabled
	 * @mbggenerated
	 */
	public Boolean getIsEnabled() {
		return isEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.is_enabled
	 * 
	 * @param isEnabled
	 *            the value for stuff.is_enabled
	 * @mbggenerated
	 */
	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.is_locked
	 * 
	 * @return the value of stuff.is_locked
	 * @mbggenerated
	 */
	public Boolean getIsLocked() {
		return isLocked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.is_locked
	 * 
	 * @param isLocked
	 *            the value for stuff.is_locked
	 * @mbggenerated
	 */
	public void setIsLocked(Boolean isLocked) {
		this.isLocked = isLocked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.locked_date
	 * 
	 * @return the value of stuff.locked_date
	 * @mbggenerated
	 */
	public Date getLockedDate() {
		return lockedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.locked_date
	 * 
	 * @param lockedDate
	 *            the value for stuff.locked_date
	 * @mbggenerated
	 */
	public void setLockedDate(Date lockedDate) {
		this.lockedDate = lockedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.login_date
	 * 
	 * @return the value of stuff.login_date
	 * @mbggenerated
	 */
	public Date getLoginDate() {
		return loginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.login_date
	 * 
	 * @param loginDate
	 *            the value for stuff.login_date
	 * @mbggenerated
	 */
	public void setLoginDate(Date loginDate) {
		this.loginDate = loginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.login_failure_count
	 * 
	 * @return the value of stuff.login_failure_count
	 * @mbggenerated
	 */
	public Integer getLoginFailureCount() {
		return loginFailureCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.login_failure_count
	 * 
	 * @param loginFailureCount
	 *            the value for stuff.login_failure_count
	 * @mbggenerated
	 */
	public void setLoginFailureCount(Integer loginFailureCount) {
		this.loginFailureCount = loginFailureCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.login_ip
	 * 
	 * @return the value of stuff.login_ip
	 * @mbggenerated
	 */
	public String getLoginIp() {
		return loginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.login_ip
	 * 
	 * @param loginIp
	 *            the value for stuff.login_ip
	 * @mbggenerated
	 */
	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp == null ? null : loginIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.password
	 * 
	 * @return the value of stuff.password
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.password
	 * 
	 * @param password
	 *            the value for stuff.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.username
	 * 
	 * @return the value of stuff.username
	 * @mbggenerated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.username
	 * 
	 * @param username
	 *            the value for stuff.username
	 * @mbggenerated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.name
	 * 
	 * @return the value of stuff.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.name
	 * 
	 * @param name
	 *            the value for stuff.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.gender
	 * 
	 * @return the value of stuff.gender
	 * @mbggenerated
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.gender
	 * 
	 * @param gender
	 *            the value for stuff.gender
	 * @mbggenerated
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.seniority
	 * 
	 * @return the value of stuff.seniority
	 * @mbggenerated
	 */
	public Integer getSeniority() {
		return seniority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.seniority
	 * 
	 * @param seniority
	 *            the value for stuff.seniority
	 * @mbggenerated
	 */
	public void setSeniority(Integer seniority) {
		this.seniority = seniority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.age
	 * 
	 * @return the value of stuff.age
	 * @mbggenerated
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.age
	 * 
	 * @param age
	 *            the value for stuff.age
	 * @mbggenerated
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.depart
	 * 
	 * @return the value of stuff.depart
	 * @mbggenerated
	 */
	public Long getDepart() {
		return depart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.depart
	 * 
	 * @param depart
	 *            the value for stuff.depart
	 * @mbggenerated
	 */
	public void setDepart(Long depart) {
		this.depart = depart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.rank
	 * 
	 * @return the value of stuff.rank
	 * @mbggenerated
	 */
	public Integer getRank() {
		return rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.rank
	 * 
	 * @param rank
	 *            the value for stuff.rank
	 * @mbggenerated
	 */
	public void setRank(Integer rank) {
		this.rank = rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.birthday
	 * 
	 * @return the value of stuff.birthday
	 * @mbggenerated
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.birthday
	 * 
	 * @param birthday
	 *            the value for stuff.birthday
	 * @mbggenerated
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column stuff.employment_date
	 * 
	 * @return the value of stuff.employment_date
	 * @mbggenerated
	 */
	public Date getEmploymentDate() {
		return employmentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column stuff.employment_date
	 * 
	 * @param employmentDate
	 *            the value for stuff.employment_date
	 * @mbggenerated
	 */
	public void setEmploymentDate(Date employmentDate) {
		this.employmentDate = employmentDate;
	}
}