package com.attendance.manage.model;

public class SystemConfig {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_config.key
	 * @mbggenerated
	 */
	private String key;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_config.value
	 * @mbggenerated
	 */
	private String value;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_config.key
	 * @return  the value of system_config.key
	 * @mbggenerated
	 */
	public String getKey() {
		return key;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_config.key
	 * @param key  the value for system_config.key
	 * @mbggenerated
	 */
	public void setKey(String key) {
		this.key = key == null ? null : key.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_config.value
	 * @return  the value of system_config.value
	 * @mbggenerated
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_config.value
	 * @param value  the value for system_config.value
	 * @mbggenerated
	 */
	public void setValue(String value) {
		this.value = value == null ? null : value.trim();
	}
}