package com.attendance.manage.model;

import java.util.Date;

public class VacationInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vacation_info.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vacation_info.create_date
	 * @mbggenerated
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vacation_info.modify_date
	 * @mbggenerated
	 */
	private Date modifyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vacation_info.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vacation_info.days
	 * @mbggenerated
	 */
	private Integer days;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vacation_info.seniority
	 * @mbggenerated
	 */
	private Integer seniority;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vacation_info.id
	 * @return  the value of vacation_info.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vacation_info.id
	 * @param id  the value for vacation_info.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vacation_info.create_date
	 * @return  the value of vacation_info.create_date
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vacation_info.create_date
	 * @param createDate  the value for vacation_info.create_date
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vacation_info.modify_date
	 * @return  the value of vacation_info.modify_date
	 * @mbggenerated
	 */
	public Date getModifyDate() {
		return modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vacation_info.modify_date
	 * @param modifyDate  the value for vacation_info.modify_date
	 * @mbggenerated
	 */
	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vacation_info.name
	 * @return  the value of vacation_info.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vacation_info.name
	 * @param name  the value for vacation_info.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vacation_info.days
	 * @return  the value of vacation_info.days
	 * @mbggenerated
	 */
	public Integer getDays() {
		return days;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vacation_info.days
	 * @param days  the value for vacation_info.days
	 * @mbggenerated
	 */
	public void setDays(Integer days) {
		this.days = days;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vacation_info.seniority
	 * @return  the value of vacation_info.seniority
	 * @mbggenerated
	 */
	public Integer getSeniority() {
		return seniority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vacation_info.seniority
	 * @param seniority  the value for vacation_info.seniority
	 * @mbggenerated
	 */
	public void setSeniority(Integer seniority) {
		this.seniority = seniority;
	}
}